version: 0.2

phases:
  install:
    commands:
      - echo Install node 12...
      - curl -sL https://deb.nodesource.com/setup_12.x | -E bash -
      - apt-get install -y nodejs
      # install Yarn
    pre_build:
      commands:
        # install dependencies
        - npm install
    build:
      commands:
        #test
        - echo Building...
        - npm build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: public
